name: Build and deploy serverless application on Kubernetes

runs:
  using: "composite"
  steps:
    - name: dummy1
      shell: bash
      run: |
        echo "dummy1"
        # echo "Environment variable ENV_NAME: ${{ vars.ENV_NAME }}"
        sleep 2s
        pwd
        ls
