name: Build and deploy serverless application on ZBI Kubernetes

inputs:
  environment:
    description: 'The target environment (dev or prod)'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: dummy
      shell: bash
      run: |
        echo "Deploying to ${{ input.environment }}"
        sleep 4s
        pwd
        ls
