name: Build and deploy serverless application on ZBI Kubernetes

runs:
  using: "composite"
  steps:
    - name: dummy
      run: |
        echo "I'm running when PR is rasied"
        sleep 4s
        pwd
        ls
