name: Build and push container images

inputs:
  docker_repo:
    required: true
    type: string
secrets:
  DOCKER_PASSWORD:
    required: true
  GH_PAT:
    required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v3
        with:
          repository: seannguyn/deployment
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: deployment

      - name: Checkout Source Code Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          path: app

      - name: Set Variables
        id: set-vars
        working-directory: app
        run: |
          pwd
          ls
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=${{ inputs.docker_repo }}/$(basename ${{ github.repository }})
          REPO_NAME=$(basename ${{ github.repository }})
          ORG_NAME=${{ github.repository_owner }}
          BRANCH=$REPO_NAME-${{ github.sha }}-deployment

          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"
          echo "ORG_NAME=$ORG_NAME" >> "$GITHUB_ENV"
          echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "REPO_NAME=$REPO_NAME" >> "$GITHUB_OUTPUT"
          echo "ORG_NAME=$ORG_NAME" >> "$GITHUB_OUTPUT"
          echo "BRANCH=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Enable Docker BuildKit
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
          echo "BUILDX_NO_DEFAULT_ATTESTATIONS=1" >> $GITHUB_ENV

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container   # 👈 Use docker-container driver
          driver-opts: network=host

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_repo }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-container
        uses: docker/build-push-action@v6
        with:
          context: "./app"
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          file: ./deployment/dockerfiles/SSaaS.Dockerfile
