name: Build and deploy serverless application on ZBI Kubernetes

on:
  workflow_call:
    inputs:
      docker_repo:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
      GH_PAT:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Build and push container image to dockerhub"
        uses: seannguyn/actions/.github/actions/build-push@main
        with:
          docker_repo: ${{ vars.DOCKER_REPO }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
  create-pr-in-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: "Build and push container image to dockerhub"
        uses: seannguyn/actions/.github/actions/deploy-PR@main
